### ISSUE TITLE
This doesn't seem to work in Firefox or Edge, Chrome only

### ISSUE THREAD

**Issue by JonathanHess** [adesigns/jquery-inactivity-timeout#3]

**Comment by mikeyudin** [comment]
I just loaded the demo (http://adesigns.github.io/jquery-inactivity-timeout) on the latest version of Firefox and it worked.  I don't have Edge on this computer to test right now.

**Comment by JonathanHess** [comment]
You're right, it does. I had Fiddler running and the demo worked fine in conjunction with Chrome but was failing to get jquery from CDN with Fiddler on... My bad. 

Fiddler closed, demo works. Thanks and my apologies for the confusion.
